# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{google_apps_api}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Stuart"]
  s.date = %q{2010-05-05}
  s.description = %q{APIs for Google Apps (currently Provisioning, Calendar, Calendar Resources)}
  s.email = %q{tastyhat@jamesstuart.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "google_apps_api.gemspec",
     "lib/config/calendar.yml",
     "lib/config/provisioning.yml",
     "lib/google_apps_api.rb",
     "lib/google_apps_api/base_api.rb",
     "lib/google_apps_api/calendar.rb",
     "lib/google_apps_api/calendar_resources.rb",
     "lib/google_apps_api/contacts.rb",
     "lib/google_apps_api/exceptions.rb",
     "lib/google_apps_api/provisioning.rb",
     "lib/google_apps_api/user_profiles.rb",
     "lib/load_config.rb",
     "private/gapps-config.yml",
     "private/userscalendars.xml",
     "test/google_apps_api-calendar_resources_test.rb",
     "test/google_apps_api_calendar_test.rb",
     "test/google_apps_api_contacts_test.rb",
     "test/google_apps_api_provisioning_test.rb",
     "test/google_apps_api_user_profiles_test.rb",
     "test/helper.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/tastyhat/google_apps_api}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Various APIs for Google Apps}
  s.test_files = [
    "test/google_apps_api-calendar_resources_test.rb",
     "test/google_apps_api_calendar_test.rb",
     "test/google_apps_api_contacts_test.rb",
     "test/google_apps_api_provisioning_test.rb",
     "test/google_apps_api_user_profiles_test.rb",
     "test/helper.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httpclient>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<httpclient>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<httpclient>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

